apiVersion: 1
datasources:
- name: Loki
  type: loki
  url: http://loki:3100
  isDefault: true
  uid: loki
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: "\"trace_id\":\"(\\w+)\""
        name: trace_id
        # url will be interpreted as query for the datasource
        url: '$${__value.raw}'
- name: Tempo
  type: tempo
  url: http://tempo:3200
  uid: tempo
  nodeGraph:
    enabled: true
  search:
    hide: false
  lokiSearch:
    datasourceUid: 'loki'